apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailer
  labels:
    app: emailer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emailer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 8
  template:
    metadata:
      labels:
        app: emailer
    spec:
      containers:
        - name: emailer
          image: dhruvsha256/emailer
          envFrom:
            - configMapRef:
                name: emailer-configmap
            - secretRef:
                name: emailer-secret
